/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardLearnRouteImport } from './routes/dashboard.learn'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as DashboardTopicsCourseIdRouteImport } from './routes/dashboard.topics.$courseId'
import { Route as DashboardSubtopicsTopicIdRouteImport } from './routes/dashboard.subtopics.$topicId'
import { Route as DashboardLessonsSubtopicIdRouteImport } from './routes/dashboard.lessons.$subtopicId'
import { Route as DashboardLessonLessonIdExerciseRouteImport } from './routes/dashboard.lesson.$lessonId.exercise'

const LoginLazyRouteImport = createFileRoute('/login')()
const Error500LazyRouteImport = createFileRoute('/error-500')()
const Error404LazyRouteImport = createFileRoute('/error-404')()
const Error403LazyRouteImport = createFileRoute('/error-403')()
const Error401LazyRouteImport = createFileRoute('/error-401')()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const Error500LazyRoute = Error500LazyRouteImport.update({
  id: '/error-500',
  path: '/error-500',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-500.lazy').then((d) => d.Route))
const Error404LazyRoute = Error404LazyRouteImport.update({
  id: '/error-404',
  path: '/error-404',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-404.lazy').then((d) => d.Route))
const Error403LazyRoute = Error403LazyRouteImport.update({
  id: '/error-403',
  path: '/error-403',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-403.lazy').then((d) => d.Route))
const Error401LazyRoute = Error401LazyRouteImport.update({
  id: '/error-401',
  path: '/error-401',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-401.lazy').then((d) => d.Route))
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLearnRoute = DashboardLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTopicsCourseIdRoute = DashboardTopicsCourseIdRouteImport.update({
  id: '/topics/$courseId',
  path: '/topics/$courseId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubtopicsTopicIdRoute =
  DashboardSubtopicsTopicIdRouteImport.update({
    id: '/subtopics/$topicId',
    path: '/subtopics/$topicId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLessonsSubtopicIdRoute =
  DashboardLessonsSubtopicIdRouteImport.update({
    id: '/lessons/$subtopicId',
    path: '/lessons/$subtopicId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLessonLessonIdExerciseRoute =
  DashboardLessonLessonIdExerciseRouteImport.update({
    id: '/lesson/$lessonId/exercise',
    path: '/lesson/$lessonId/exercise',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/error-401': typeof Error401LazyRoute
  '/error-403': typeof Error403LazyRoute
  '/error-404': typeof Error404LazyRoute
  '/error-500': typeof Error500LazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/lessons/$subtopicId': typeof DashboardLessonsSubtopicIdRoute
  '/dashboard/subtopics/$topicId': typeof DashboardSubtopicsTopicIdRoute
  '/dashboard/topics/$courseId': typeof DashboardTopicsCourseIdRoute
  '/dashboard/lesson/$lessonId/exercise': typeof DashboardLessonLessonIdExerciseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/error-401': typeof Error401LazyRoute
  '/error-403': typeof Error403LazyRoute
  '/error-404': typeof Error404LazyRoute
  '/error-500': typeof Error500LazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/lessons/$subtopicId': typeof DashboardLessonsSubtopicIdRoute
  '/dashboard/subtopics/$topicId': typeof DashboardSubtopicsTopicIdRoute
  '/dashboard/topics/$courseId': typeof DashboardTopicsCourseIdRoute
  '/dashboard/lesson/$lessonId/exercise': typeof DashboardLessonLessonIdExerciseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/error-401': typeof Error401LazyRoute
  '/error-403': typeof Error403LazyRoute
  '/error-404': typeof Error404LazyRoute
  '/error-500': typeof Error500LazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/lessons/$subtopicId': typeof DashboardLessonsSubtopicIdRoute
  '/dashboard/subtopics/$topicId': typeof DashboardSubtopicsTopicIdRoute
  '/dashboard/topics/$courseId': typeof DashboardTopicsCourseIdRoute
  '/dashboard/lesson/$lessonId/exercise': typeof DashboardLessonLessonIdExerciseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/login'
    | '/dashboard/achievements'
    | '/dashboard/courses'
    | '/dashboard/learn'
    | '/dashboard/users'
    | '/dashboard/lessons/$subtopicId'
    | '/dashboard/subtopics/$topicId'
    | '/dashboard/topics/$courseId'
    | '/dashboard/lesson/$lessonId/exercise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/login'
    | '/dashboard/achievements'
    | '/dashboard/courses'
    | '/dashboard/learn'
    | '/dashboard/users'
    | '/dashboard/lessons/$subtopicId'
    | '/dashboard/subtopics/$topicId'
    | '/dashboard/topics/$courseId'
    | '/dashboard/lesson/$lessonId/exercise'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/login'
    | '/dashboard/achievements'
    | '/dashboard/courses'
    | '/dashboard/learn'
    | '/dashboard/users'
    | '/dashboard/lessons/$subtopicId'
    | '/dashboard/subtopics/$topicId'
    | '/dashboard/topics/$courseId'
    | '/dashboard/lesson/$lessonId/exercise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  Error401LazyRoute: typeof Error401LazyRoute
  Error403LazyRoute: typeof Error403LazyRoute
  Error404LazyRoute: typeof Error404LazyRoute
  Error500LazyRoute: typeof Error500LazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-500': {
      id: '/error-500'
      path: '/error-500'
      fullPath: '/error-500'
      preLoaderRoute: typeof Error500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-404': {
      id: '/error-404'
      path: '/error-404'
      fullPath: '/error-404'
      preLoaderRoute: typeof Error404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-403': {
      id: '/error-403'
      path: '/error-403'
      fullPath: '/error-403'
      preLoaderRoute: typeof Error403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-401': {
      id: '/error-401'
      path: '/error-401'
      fullPath: '/error-401'
      preLoaderRoute: typeof Error401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/learn': {
      id: '/dashboard/learn'
      path: '/learn'
      fullPath: '/dashboard/learn'
      preLoaderRoute: typeof DashboardLearnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/topics/$courseId': {
      id: '/dashboard/topics/$courseId'
      path: '/topics/$courseId'
      fullPath: '/dashboard/topics/$courseId'
      preLoaderRoute: typeof DashboardTopicsCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subtopics/$topicId': {
      id: '/dashboard/subtopics/$topicId'
      path: '/subtopics/$topicId'
      fullPath: '/dashboard/subtopics/$topicId'
      preLoaderRoute: typeof DashboardSubtopicsTopicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lessons/$subtopicId': {
      id: '/dashboard/lessons/$subtopicId'
      path: '/lessons/$subtopicId'
      fullPath: '/dashboard/lessons/$subtopicId'
      preLoaderRoute: typeof DashboardLessonsSubtopicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lesson/$lessonId/exercise': {
      id: '/dashboard/lesson/$lessonId/exercise'
      path: '/lesson/$lessonId/exercise'
      fullPath: '/dashboard/lesson/$lessonId/exercise'
      preLoaderRoute: typeof DashboardLessonLessonIdExerciseRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardLearnRoute: typeof DashboardLearnRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardLessonsSubtopicIdRoute: typeof DashboardLessonsSubtopicIdRoute
  DashboardSubtopicsTopicIdRoute: typeof DashboardSubtopicsTopicIdRoute
  DashboardTopicsCourseIdRoute: typeof DashboardTopicsCourseIdRoute
  DashboardLessonLessonIdExerciseRoute: typeof DashboardLessonLessonIdExerciseRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardLearnRoute: DashboardLearnRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardLessonsSubtopicIdRoute: DashboardLessonsSubtopicIdRoute,
  DashboardSubtopicsTopicIdRoute: DashboardSubtopicsTopicIdRoute,
  DashboardTopicsCourseIdRoute: DashboardTopicsCourseIdRoute,
  DashboardLessonLessonIdExerciseRoute: DashboardLessonLessonIdExerciseRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  Error401LazyRoute: Error401LazyRoute,
  Error403LazyRoute: Error403LazyRoute,
  Error404LazyRoute: Error404LazyRoute,
  Error500LazyRoute: Error500LazyRoute,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
